services:
  - type: web
    name: dusklight
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SECRET_KEY
        value: set-a-strong-secret-key-here
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
